name: Pandeia
favicon: null
layout_spectrum: 0.30666812555864453
typography_spectrum: 0.691932765301317
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6319263728801161
  lightness: 0.1251244954764843
  saturation: 0.5317872776649892
  rhythmicContrast: 0.32497593248263
purpose: []
